[Metadata]
Name=dwm
Version=1.0
Author=seriola
Description=A minimal, flat theme inspired by dwm.
ScaleWithDPI=True

[InputPanel]
EnableBlur=False
NormalColor=#bbbbbb
HighlightCandidateColor=#eeeeee
HighlightColor=#eeeeee
HighlightBackgroundColor=#005577
Spacing=2

[InputPanel/ShadowMargin]
Left=0
Right=0
Top=0
Bottom=0

[InputPanel/BlurMargin]
Left=0
Right=0
Top=0
Bottom=0

[InputPanel/ContentMargin]
Left=4
Right=4
Top=4
Bottom=4

[InputPanel/TextMargin]
Left=4
Right=4
Top=4
Bottom=4

[InputPanel/Background]
Color=#222222

[InputPanel/Background/Margin]
Left=2
Right=2
Top=2
Bottom=2

[InputPanel/Highlight]
Color=#005577

[InputPanel/Highlight/Margin]
Left=4
Right=4
Top=4
Bottom=4

[InputPanel/PrevPage]
Color=#bbbbbb

[InputPanel/PrevPage/ClickMargin]
Left=0
Right=0
Top=0
Bottom=0

[InputPanel/NextPage]
Color=#bbbbbb

[InputPanel/NextPage/ClickMargin]
Left=0
Right=0
Top=0
Bottom=0
