let s:config = empty($XDG_CONFIG_HOME) ? expand("~/.config") : expand("$XDG_CONFIG_HOME")
let s:data   = empty($XDG_DATA_HOME)   ? expand("~/.local/share") : expand("$XDG_DATA_HOME")
let s:state  = empty($XDG_STATE_HOME)  ? expand("~/.local/state") : expand("$XDG_STATE_HOME")

if isdirectory(s:config . '/vim')
  function! s:mkvimdir(dir)
    if !isdirectory(a:dir)
      call mkdir(a:dir, 'p', 0700)
    endif
    return a:dir
  endfunction

  " Use Data for packages, prevent duplicates
  if index(split(&packpath, ','), s:data . '/vim') == -1
    execute 'set packpath^=' . s:data . '/vim'
    execute 'set packpath+=' . s:data . '/vim/after'
  endif

  " Persistent Data:
  let &undodir = s:mkvimdir(s:data . '/vim/undo')
  let &viewdir = s:mkvimdir(s:data . '/vim/view')
  let g:netrw_home = s:mkvimdir(s:data . '/vim')
  call s:mkvimdir(s:data . '/vim/spell')

  " Transient State:
  let &viminfofile = s:mkvimdir(s:state . '/vim') . '/viminfo'
  let &directory  = s:mkvimdir(s:state . '/vim/swap')   . '//'
  let &backupdir   = s:mkvimdir(s:state . '/vim/backup') . '//'

  delfunction! s:mkvimdir
endif

unlet s:config s:data s:state

xnoremap "+y y:call system("wl-copy", @")<cr>
nnoremap "+p :let @"=substitute(system("wl-paste --no-newline"), '<C-v><C-m>', '', 'g')<cr>p
nnoremap "*p :let @"=substitute(system("wl-paste --no-newline --primary"), '<C-v><C-m>', '', 'g')<cr>p
xnoremap "+p :<C-u>let @z=substitute(system("wl-paste --no-newline"), '<C-v><C-m>', '', 'g')<cr>gv"zp
xnoremap "*p :<C-u>let @z=substitute(system("wl-paste --no-newline --primary"), '<C-v><C-m>', '', 'g')<cr>gv"zp
nnoremap "+d d:call system("wl-copy", @")<cr>
xnoremap "+d d:call system("wl-copy", @")<cr>

filetype plugin indent on
syntax on

set undofile
set relativenumber

set incsearch
set hlsearch
set ignorecase
set smartcase

set expandtab
set tabstop=4
set shiftwidth=4

set smartindent

set cc=80

set backspace=indent,eol,start

cmap w!! w !sudo tee > /dev/null %

function! FzyCommand(choice_command, vim_command)
  try
    let output = system(a:choice_command . " | fzy ")
  catch /vim:Interrupt/
    " Swallow errors from ^C, allow redraw! below
  endtry
  redraw!
  if v:shell_error == 0 && !empty(output)
    exec a:vim_command . ' ' . output
  endif
endfunction

nnoremap <leader>vsp :call FzyCommand("find . -type f", ":vsp")<cr>
