runtime xdg.vim

let s:data   = empty($XDG_DATA_HOME)   ? expand("~/.local/share") : expand("$XDG_DATA_HOME")
let s:state  = empty($XDG_STATE_HOME)  ? expand("~/.local/state") : expand("$XDG_STATE_HOME")

func s:mkvimdir(dir)
  if !isdirectory(a:dir)
    call mkdir(a:dir, 'p', 0700)
  endif
  return a:dir
endfunc

" Persistent Data:
let &undodir = s:mkvimdir(s:data .. '/vim/undo')
let &viewdir = s:mkvimdir(s:data .. '/vim/view')
let g:netrw_home = s:mkvimdir(s:data .. '/vim')
call s:mkvimdir(s:data .. '/vim/spell')

" Transient State:
let &directory = s:mkvimdir(s:state .. '/vim/swap')   .. '//'
let &backupdir = s:mkvimdir(s:state .. '/vim/backup') .. '//'

delfunction s:mkvimdir
unlet s:data s:state

filetype plugin indent on
syntax on

set undofile
set relativenumber
set ruler 

set incsearch
set hlsearch
set ignorecase
set smartcase

set expandtab
set tabstop=4
set shiftwidth=4

set smartindent

set cc=80

cmap w!! w !sudo tee > /dev/null %

function! FzyCommand(choice_command, vim_command)
  try
    let output = system(a:choice_command . " | fzy ")
  catch /vim:Interrupt/
    " Swallow errors from ^C, allow redraw! below
  endtry
  redraw!
  if v:shell_error == 0 && !empty(output)
    exec a:vim_command . ' ' . output
  endif
endfunction

nnoremap <leader>vsp :call FzyCommand("find . -type f", ":vsp")<cr>
