[key-bindings]
scrollback-up-half-page=Control+k
scrollback-down-half-page=Control+j

font-increase=Control+equal
font-decrease=Control+minus

show-urls-launch=Control+Shift+f
show-urls-copy=Control+Shift+y

spawn-terminal=Control+Shift+m

search-start=Control+slash

[search-bindings]
# unmap the default to avoid conflicting bindings
delete-to-end=none
find-prev=Control+p
find-next=Control+n
extend-char=Control+l
extend-backward-char=Control+h
extend-line-down=Control+j
extend-line-up=Control+k
extend-to-word-boundary=Control+w
commit=Return
